version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Warsaw
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DOCKER_DB_PORT}
  blog:
    container_name: be
    image: blog_be
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:${DOCKER_BE_PORT}
    environment:
      - TZ=Europe/Warsaw
#    volumes:
#      - .:/blog
    ports:
      - ${BE_PORT}:${DOCKER_BE_PORT}
    depends_on:
      - db
volumes:
  db:
    driver: local
