# Generated by Django 4.1 on 2022-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_server", "0002_remove_comment_active_alter_comment_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(verbose_name="Created"),
        ),
    ]
